apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    name: PROJECT9-APPLE9-httpd-log-pv
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 1Mi
    nfs:
      path: /openshift/PROJECT9/APPLE9-httpd/log/
      server: efs.ocp-dev.hanwhalife.com
    persistentVolumeReclaimPolicy: Retain
    storageClassName: aws-efs
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    namespace: PROJECT9
    annotations:
    finalizers:
    - kubernetes.io/pvc-protection
    name: PROJECT9-APPLE9-httpd-log-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Mi
    volumeName: PROJECT9-APPLE9-httpd-log-pv
    storageClassName: aws-efs
kind: List
